# Generated by Django 4.2.1 on 2023-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('available_time', models.CharField(choices=[('free', 'Free'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=100)),
                ('education', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('degree', 'Degree'), ('master', 'Master'), ('other', 'Other')], max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
