# Generated by Django 4.2.1 on 2023-07-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
